label2idx = {
    "Autoladestation": 0,
    "Ladestation PW": 0,
    "Beleuchtung": 1,
    "Blockspeicher": 2,
    "Batteriespeicher": 2,
    "Boiler": 3,
    "Direktheizung": 4,
    "Doppeltarif/Privatzähler": 5,
    "Einspeiser Photovoltaik Anlage": 6,
    "ES Photovoltaik Anlage": 6,
    "Einzelspeicher": 7,
    "Saunaofen": 8,
    "Tumbler": 9,
    "Unknown": 10,
    "WP Boiler": 11,
    "WP-Boiler": 11,
    "Waschmaschine": 12,
    "Waschmaschine und Tumbler": 13,
    "Waschmaschine Tumbler": 13,
    "Wärmepumpe": 14,
}

idx2label = {
    0: "Ladestation PW",
    1: "Beleuchtung",
    2: "Batteriespeicher",
    3: "Boiler",
    4: "Direktheizung",
    5: "Doppeltarif/Privatzähler",
    6: "ES Photovoltaik Anlage",
    7: "Einzelspeicher",
    8: "Saunaofen",
    9: "Tumbler",
    10: "Unknown",
    11: "WP-Boiler",
    12: "Waschmaschine",
    13: "Waschmaschine Tumbler",
    14: "Wärmepumpe",
}
